### ISSUE TITLE
Example gets stuck trying to discover Chromecast devices

### ISSUE THREAD

**Issue by ryanheise** [gianlucaparadise/flutter_cast_framework#5]
When I run the example on my Google Pixel 3a, and click the Chromecast button, it shows a dialog where it searches for Chromecast devices. That dialog searches forever without success. The Chromecast is on, and other apps can discover it.

**Comment by MatthiasWissink** [comment]
Did you change the receiverApplicationId in CastOptionsProvider in the android project? 
You can use the default `CC1AD845` receiver ID
After that the example worked for me

**Comment by ryanheise** [comment]
Thanks @MatthiasWissink . I only ran the example as is without checking it so I didn't spot that - @gianlucaparadise perhaps it would be a good idea for the default example  in this repo to also use the default receiver ID?

**Comment by gianlucaparadise** [comment]
Did it work using the default receiver ID? The receiver ID of the example points to a custom web receiver that showcases the feature of the example sender.
If it worked with the default receiver ID, than there is a problem on the custom receiver and I can look into it.

**Comment by MatthiasWissink** [comment]
Yes, I have the example working with the default receiver ID. When using the one that comes in the repo, I get the same loading/searching issue as @ryanheise

**Comment by gianlucaparadise** [comment]
Can you please try again? I just published the custom receiver.

**Comment by MatthiasWissink** [comment]
Still the same behavior running the example as it is.
But I also saw that the receiver ID in example/android (`D6760CCD`) is different from the one in root/android (`4F8B3483`). Only using this ID or the default ID works.

**Comment by markst** [comment]
@MatthiasWissink is there an Android equivalent to `kGCKDefaultMediaReceiverApplicationID`?

----
Edit: 
Looks like there's `DEFAULT_MEDIA_RECEIVER_APPLICATION_ID`
Might open a PR to use these constants in example rather than `D6760CCD` / `4F8B3483` as mentioned.

**Comment by markst** [comment]
> The receiver ID of the example points to a custom web receiver that showcases the feature of the example sender.

@gianlucaparadise Care to share how to use the custom web receiver?
